require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const { errors } = require('celebrate');
const authRoutes = require('./routes/auth.routes');
const itRoutes = require('./routes/itineraries.routes');
const errorHandler = require('./middleware/error.middleware');
const setupSwagger = require('./config/swagger');
const { apiLimiter } = require('./middleware/rateLimiter');
const app = express();
app.use(helmet());
app.use(cors());
app.use(morgan('dev'));
app.use(express.json());
app.use('/api', apiLimiter);
app.use('/api/auth', authRoutes);
app.use('/api/itineraries', itRoutes);
setupSwagger(app);
app.get('/ping', (req, res) => res.send('pong'));
app.use(errors());
app.use(errorHandler);
module.exports = app;
